import logging
from typing import Any, Dict, Optional

from modules.analysis.classification_rules import (
    classify_failure_pattern,
)

logger = logging.getLogger(__name__)


class FailureClassifier:
    """
    Classifies the current API test result using historical
    Datadog execution data.

    Possible classifications include:
        - New Failure
        - Persistent Failure
        - Flaky Failure
        - Resolved Failure
        - Healthy
    """

    def __init__(self):
        logger.info("Failure classifier initialized")

    # ------------------------------------------------------------------
    # Main classification method
    # ------------------------------------------------------------------

    def classify(
        self,
        current_result,
        historical_data: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Classify the current test result.

        Args:
            current_result:
                Current K6TestResult object.

            historical_data:
                Historical analysis generated by HistoricalAnalyzer.

        Returns:
            Classification dictionary.
        """

        service = current_result.service.lower()
        test_name = current_result.test_name.lower()
        current_status = current_result.status.upper()

        historical_data = historical_data or {}

        statuses = historical_data.get(
            "statuses",
            [],
        )

        failure_rate = historical_data.get(
            "failure_rate",
            0.0,
        )

        total_executions = historical_data.get(
            "total_executions",
            0,
        )

        passed = historical_data.get(
            "passed",
            0,
        )

        failed = historical_data.get(
            "failed",
            0,
        )

        trend = historical_data.get(
            "trend",
            "NO_HISTORY",
        )

        logger.debug(
            "Classifying %s/%s: current=%s, "
            "history=%d executions",
            service,
            test_name,
            current_status,
            total_executions,
        )

        # --------------------------------------------------------------
        # Build historical context expected by classification rules
        # --------------------------------------------------------------

        history = {
            "statuses": statuses,
            "failure_rate": failure_rate,
            "total_executions": total_executions,
            "passed": passed,
            "failed": failed,
            "trend": trend,
        }

        # --------------------------------------------------------------
        # Apply classification rules
        # --------------------------------------------------------------

        try:
            classification = classify_failure_pattern(
                current_status=current_status,
                historical_data=history,
            )

        except TypeError:
            # Backward-compatible fallback in case the existing
            # classification_rules.py expects the historical list
            # directly instead of a dictionary.
            classification = classify_failure_pattern(
                current_status,
                statuses,
            )

        # --------------------------------------------------------------
        # Normalize result
        # --------------------------------------------------------------

        if isinstance(classification, str):
            classification_name = classification

            result = {
                "classification": classification_name,
                "service": service,
                "test": test_name,
                "current_status": current_status,
                "historical_executions": total_executions,
                "historical_passed": passed,
                "historical_failed": failed,
                "historical_failure_rate": failure_rate,
                "historical_trend": trend,
                "statuses": statuses,
            }

        elif isinstance(classification, dict):
            result = dict(classification)

            result.setdefault(
                "classification",
                result.get("pattern", "Unknown"),
            )

            result.setdefault(
                "service",
                service,
            )

            result.setdefault(
                "test",
                test_name,
            )

            result.setdefault(
                "current_status",
                current_status,
            )

            result.setdefault(
                "historical_executions",
                total_executions,
            )

            result.setdefault(
                "historical_passed",
                passed,
            )

            result.setdefault(
                "historical_failed",
                failed,
            )

            result.setdefault(
                "historical_failure_rate",
                failure_rate,
            )

            result.setdefault(
                "historical_trend",
                trend,
            )

            result.setdefault(
                "statuses",
                statuses,
            )

        else:
            result = {
                "classification": "Unknown",
                "service": service,
                "test": test_name,
                "current_status": current_status,
                "historical_executions": total_executions,
                "historical_passed": passed,
                "historical_failed": failed,
                "historical_failure_rate": failure_rate,
                "historical_trend": trend,
                "statuses": statuses,
            }

        logger.info(
            "Classification for %s/%s: %s",
            service,
            test_name,
            result["classification"],
        )

        return result